kind: ConfigMap
apiVersion: v1
metadata:
  name: homelab-mcp-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-otel-collector.signoz.svc.cluster.local:4318
  LOG_LEVEL: info
  AUTH_SERVER_URL: https://oauth.apps.dev-01.6cclab.dev
