apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/anpato/ot-knowledge-mcp
  newName: ghcr.io/anpato/ot-knowledge-mcp
  newTag: c679880ff37883aa6e5c338c30b765b6ccc38258

patches:
- path: ./deployment.yaml

resources:
- ../../base
- ingress.yaml
- infisical-secret.yaml
