apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/6cclab/homelab/homelab-mcp
  newName: ghcr.io/6cclab/homelab/homelab-mcp
  newTag: e07202461c6def62a8e297ab8c45b41063a28e4d
patches:
- path: ./deployment.yaml
resources:
- ../../base
- ingress.yaml
