apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/6cclab/homelab/homelab-mcp
  newName: ghcr.io/6cclab/homelab/homelab-mcp
  newTag: 08f6a66025c04de05361cc0fe134242660bf44a1
patches:
- path: ./deployment.yaml
resources:
- ../../base
- ingress.yaml
