apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/6cclab/homelab/homelab-mcp
  newName: ghcr.io/6cclab/homelab/homelab-mcp
  newTag: 0d47fc5d959ecad85245bc417ba6f410669a4ea0
patches:
- path: ./deployment.yaml
resources:
- ../../base
- ingress.yaml
